version: 2

sources:
  - name: globalmart
    description: a clone of Snowflake Database
    schema: raw
    tables:
      - name: customers
      - name: orders
        description: raw orders table
        columns:
          - name: orderid
            description: primary key for orders
            tests:
              - unique
              - not_null
      - name: products

        


    

             
    
    