version: 2

sources:
  - name: globalmart
    schema: raw
    tables:
      - name: customers
      - name: orders
        columns:
          - name: orderid
            tests:
              - unique
              - not_null
      - name: products

        


    

             
    
    